module.exports = {
    extends: ['cz-git'],
    prompt: {
        types: [
            { value: 'feat', name: 'feat:     ✨ A new feature', emoji: ':sparkles:' },
            { value: 'fix', name: 'fix:      🐛 A bug fix', emoji: ':bug:' },
            { value: 'docs', name: 'docs:     📝 Documentation only changes', emoji: ':memo:' },
            { value: 'style', name: 'style:    💄 Code style changes (formatting, etc)', emoji: ':lipstick:' },
            { value: 'refactor', name: 'refactor: ♻️  Code refactoring', emoji: ':recycle:' },
            { value: 'perf', name: 'perf:     ⚡️ Performance improvements', emoji: ':zap:' },
            { value: 'test', name: 'test:     ✅ Adding or updating tests', emoji: ':white_check_mark:' },
            { value: 'build', name: 'build:    📦 Build system or dependencies', emoji: ':package:' },
            { value: 'ci', name: 'ci:       👷 CI configuration changes', emoji: ':construction_worker:' },
            { value: 'chore', name: 'chore:    🔧 Other changes that don\'t modify src', emoji: ':wrench:' },
            { value: 'revert', name: 'revert:   ⏪️ Revert a previous commit', emoji: ':rewind:' }
        ],
        useEmoji: true,
        emojiAlign: 'center',
        allowCustomScopes: true,
        allowEmptyScopes: true,
        customScopesAlign: 'bottom',
        emptyScopesAlias: 'empty',
        upperCaseSubject: false,
        markBreakingChangeMode: false,
        breaklineNumber: 100,
        breaklineChar: '|',
        skipQuestions: [],
        issuePrefixes: [{ value: 'closed', name: 'closed:   ISSUES has been processed' }],
        customIssuePrefixAlign: 'top',
        emptyIssuePrefixAlias: 'skip',
        customIssuePrefixAlias: 'custom',
        allowCustomIssuePrefix: true,
        allowEmptyIssuePrefix: true,
        confirmColorize: true,
        maxHeaderLength: Infinity,
        maxSubjectLength: Infinity,
        minSubjectLength: 0,
        scopeOverrides: undefined,
        defaultBody: '',
        defaultIssues: '',
        defaultScope: '',
        defaultSubject: ''
    }
};
